language: c
compiler: gcc
env:
  global:
  - MUSL_TAG=2019042701
sudo: false
script: scripts/travis-script
deploy:
  provider: releases
  api_key:
    secure: J8pzUmYgiM4BXsz6wfzUMRTp9LWN8Zkvm576WcM6vRSWvhvT1BRhbjws+pf65NvFPedHG5OpofBQTRQjnf9mBV0liVGhvaFijKuEzgsalcjQfPZjdlzaYgLZng3XMPSTOTH62fYDmH/24tLxKCH0JBi/Y5AZ1yk9WD7tC3ug5PeEeyMSUhFXbnjwH8iCqNYcLiKneHXJq1Y9ImGql4KGZOLrSh5cmE+3JoP3iQAfv5HYVh9J+fjbEDHXnOCSFsJQilMWbbV2u2wzed3z+8YN8PZXtS3fvasWb3jgZ4noOWlN6Z0zDlcCEYILBf8y3w7kRkjkJ9XOrA8lfNLt7cKx+v73+b28cjySWADF/rxJUFrsfr3k7VQOQ/49VXMkGlUDvv5iS69VUEBCU6Q5yP2MzkNCMwM2OwjFkRVfeVmTZu5mJxgpabZZKi61xLqo5DrQRSY7SVTE41auwnDdQyn7ijn0iQymo1B3f9ckdIFRjfGt2ZVhpIPYELInaxrEoo1scYSSNm+z2qPAc96NCIbFpKUQIf6am83W6/hD4sFT5i8uq1ivn+rGOjD7iEpZHyNluMCt/1AIO/HwDh5Qjc2/9Zfmso3hLFEN7i8xQXWKL8vckqPiugjR4r9apXskBckuNwY4vpdgJHaDdiS4aMs4XzBRKFb7qr7286M39yF19lE=
  skip_cleanup: true
  file_glob: true
  file:
   - undup-*.tar.gz
   #~ - alpine-v*.apk
  on:
    repo: TortugaLabs/undup
    tags: true

install:
- docker pull voidlinux/masterdir-x86_64-musl:$MUSL_TAG
- docker run -d --name void -v "$(pwd)":/hostrepo -v /tmp:/tmp -e PATH="$PATH" voidlinux/masterdir-x86_64-musl:$MUSL_TAG /bin/sh -c 'sleep inf'

notifications:
  email: false

