language: c
compiler: gcc
addons:
  apt:
    packages:
    - fakeroot
    - fakechroot
    - proot
script:
- type fakechroot
- type fakeroot
- type proot
- exit 1
- echo Standard build checks
- make GOPTZ=-O1 debug && make GOPTZ=-O1 check
- echo Build TARBALL
- make realclean
- mkdir undup-${TRAVIS_TAG:-$(git describe)}
- cp -a *.[ch] undup.1 LICENSE Makefile README.md lib regressions scripts undup-${TRAVIS_TAG:-$(git
  describe)}
- echo 'const char version[] = "'${TRAVIS_TAG:-$(git describe)}'";' > undup-${TRAVIS_TAG:-$(git
  describe)}/version.h
- cat undup-*/version.h
- tar zcf undup-${TRAVIS_TAG:-$(git describe)}.tar.gz undup-${TRAVIS_TAG:-$(git describe)}
deploy:
  provider: releases
  api_key:
    secure: J8pzUmYgiM4BXsz6wfzUMRTp9LWN8Zkvm576WcM6vRSWvhvT1BRhbjws+pf65NvFPedHG5OpofBQTRQjnf9mBV0liVGhvaFijKuEzgsalcjQfPZjdlzaYgLZng3XMPSTOTH62fYDmH/24tLxKCH0JBi/Y5AZ1yk9WD7tC3ug5PeEeyMSUhFXbnjwH8iCqNYcLiKneHXJq1Y9ImGql4KGZOLrSh5cmE+3JoP3iQAfv5HYVh9J+fjbEDHXnOCSFsJQilMWbbV2u2wzed3z+8YN8PZXtS3fvasWb3jgZ4noOWlN6Z0zDlcCEYILBf8y3w7kRkjkJ9XOrA8lfNLt7cKx+v73+b28cjySWADF/rxJUFrsfr3k7VQOQ/49VXMkGlUDvv5iS69VUEBCU6Q5yP2MzkNCMwM2OwjFkRVfeVmTZu5mJxgpabZZKi61xLqo5DrQRSY7SVTE41auwnDdQyn7ijn0iQymo1B3f9ckdIFRjfGt2ZVhpIPYELInaxrEoo1scYSSNm+z2qPAc96NCIbFpKUQIf6am83W6/hD4sFT5i8uq1ivn+rGOjD7iEpZHyNluMCt/1AIO/HwDh5Qjc2/9Zfmso3hLFEN7i8xQXWKL8vckqPiugjR4r9apXskBckuNwY4vpdgJHaDdiS4aMs4XzBRKFb7qr7286M39yF19lE=
  skip_cleanup: true
  file_glob: true
  file:
   - undup-*.tar.gz
  on:
    repo: TortugaLabs/undup
    tags: true
