= UNDUP(1)
:doctype:	manpage
:Date:	2019-04-10
:man manual:	User commands
:man source:	undup.c
:Author: A Liu Ly
:Revision: 2.0

== NAME

undup - tracks duplicate files and merges them with hardlinks

== SYNOPSIS

*undup* [options] [directory]

== DESCRIPTION

*undup(1)* examines the contents of a filesystem (directory) searching
for file duplicates.  When found, it saves diskspace by replacing
repeated files with hardlinks.

By default *NO CHANGES* are made on the filesystem, and only
shows what would happen.  To execute changes you need to use
option *-e* (execute).

== OPTIONS

*-5*::
   use MD5 for hashes
*-C*::
   disables hash caching
*-c* catalogue::
   create a file catalogue
*-e*::
   creates hardlinks (disables the default, dry-run mode)
*-H* algo::
   Sets the hash algo to *algo*.
*-h*::
   show help information
*-I* pattern::
   Add an include pattern.  (Start with "/" for a full path
   match.  End with "/" to match directories only)
*-K*::
   Shows caching stats
*-l* lockfile::
   create an exclusive lock (to avoid overruning)
*-m*::
   Shows memory statistics
*-q*::
   quiet mode
*-S*::
   use SHA256 for hashes
*-s*::
   only scans the file system
*-V*::
   show version info
*-v*::
   verbose mode
*-X* pattern::
   Add an exclude pattern.  (Start with "/" for a full path
   match.  End with "/" to match directories only)

== HEURISTICS

*undup(1)* this is very straight forward, it does the following
heuristics:

1. scans the filesystem recording i-nodes.  While this is happening,
   the hash cache is check to make sure that it is still valid.
2. gets files (i-nodes) that have the same size and sorts them by
   size.  Only regular files that are not empty are taken into account
   here.
3. read and compare the first bytes in each file.
4. read and compare the last bytes in each file.
5. calculate the hash of each file
6. sort all matching i-nodes by date.  Hard link all i-nodes to the
   oldest one.

When comparing files, the file permisison modes, user and group
ownership are used as distinguishing features.
The reason is that *undup(1)* is intended to be use for *live*
filesytems.  In that situation, we want to preserve permissions
and file ownerships accross deduplicated i-nodes.

== HASHES

*undup(1)* uses MD5 for the checksum by default.  The following
hashes are available (with the -H option):

* md5 (Option -5)
* md2
* sha1
* sha256 (Option -S)

