'\" t
.\"     Title: undup
.\"    Author: A Liu Ly
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2015-11-25
.\"    Manual: User commands
.\"    Source: undup.c 2.0
.\"  Language: English
.\"
.TH "UNDUP" "1" "2015\-11\-25" "undup\&.c 2\&.0" "User commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
undup \- tracks duplicate files and merges them with hardlinks
.SH "SYNOPSIS"
.sp
\fBundup\fR [options] [directory]
.SH "DESCRIPTION"
.sp
\fBundup(1)\fR examines the contents of a filesystem (directory) searching for file duplicates\&. When found, it saves diskspace by replacing repeated files with hardlinks\&.
.SH "OPTIONS"
.PP
\fB\-c\fR catalogue
.RS 4
create a file catalogue
.RE
.PP
\fB\-l\fR lockfile
.RS 4
create an exclusive lock (to avoid overruning)
.RE
.PP
\fB\-C\fR
.RS 4
disables hash caching
.RE
.PP
\fB\-e\fR
.RS 4
creates hardlinks (disables the default, dry\-run mode)
.RE
.PP
\fB\-m\fR
.RS 4
Shows memory statistics
.RE
.PP
\fB\-K\fR
.RS 4
Shows caching stats
.RE
.PP
\fB\-s\fR
.RS 4
only scans the file system
.RE
.PP
\fB\-5\fR
.RS 4
use MD5 for hashes
.RE
.PP
\fB\-S\fR
.RS 4
use SHA256 for hashes
.RE
.PP
\fB\-q\fR
.RS 4
quiet mode
.RE
.PP
\fB\-v\fR
.RS 4
verbose mode
.RE
.PP
\fB\-V\fR
.RS 4
show version info
.RE
.PP
\fB\-h\fR
.RS 4
show help information
.RE
.SH "HEURISTICS"
.sp
\fBundup(1)\fR this is very straight forward, it does the following heuristics:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
scans the filesystem recording i\-nodes\&. While this is happening, the hash cache is check to make sure that it is still valid\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
gets files (i\-nodes) that have the same size and sorts them by size\&. Only regular files that are not empty are taken into account here\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
read and compare the first bytes in each file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
read and compare the last bytes in each file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
calculate the hash of each file
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
sort all matching i\-nodes by date\&. Hard link all i\-nodes to the oldest one\&.
.RE
.sp
When comparing files, the file permisison modes, user and group ownership are used as distinguishing features\&. The reason is that \fBundup(1)\fR is intended to be use for \fBlive\fR filesytems\&. In that situation, we want to preserver permissions and file ownerships accross deduplicated i\-nodes\&.
.sp
\fBundup(1)\fR uses MD5 for the checksum by default, but it has the option to use SHA256 checksums\&.
.SH "AUTHOR"
.PP
\fBA Liu Ly\fR
.RS 4
Author.
.RE
