= UNDUP(1)
:doctype:	manpage
:Date:	2016-03-24
:man manual:	User commands
:man source:	undup.c
:Author: A Liu Ly
:Revision: 2.0

== NAME

undup - tracks duplicate files and merges them with hardlinks

== SYNOPSIS

*undup* [options] [directory]

== DESCRIPTION

*undup(1)* examines the contents of a filesystem (directory) searching
for file duplicates.  When found, it saves diskspace by replacing
repeated files with hardlinks.

== OPTIONS

*-c* catalogue::
   create a file catalogue
*-l* lockfile::
   create an exclusive lock (to avoid overruning)
*-C*::
   disables hash caching
*-e*::
   creates hardlinks (disables the default, dry-run mode)
*-m*::
   Shows memory statistics
*-K*::
   Shows caching stats
*-s*::
   only scans the file system
*-5*::
   use MD5 for hashes
*-S*::
   use SHA256 for hashes
*-q*::
   quiet mode
*-v*::
   verbose mode
*-V*::
   show version info
*-h*::
   show help information

== HEURISTICS

*undup(1)* this is very straight forward, it does the following
heuristics:

1. scans the filesystem recording i-nodes.  While this is happening,
   the hash cache is check to make sure that it is still valid.
2. gets files (i-nodes) that have the same size and sorts them by
   size.  Only regular files that are not empty are taken into account
   here.
3. read and compare the first bytes in each file.
4. read and compare the last bytes in each file.
5. calculate the hash of each file
6. sort all matching i-nodes by date.  Hard link all i-nodes to the
   oldest one.

When comparing files, the file permisison modes, user and group
ownership are used as distinguishing features.
The reason is that *undup(1)* is intended to be use for *live*
filesytems.  In that situation, we want to preserver permissions
and file ownerships accross deduplicated i-nodes.

*undup(1)* uses MD5 for the checksum by default, but it has the
option to use SHA256 checksums.

