#!/usr/bin/perl -w
#
#    This file is part of undup
#    Copyright (C) 2015, Alejandro Liu
#
#    undup is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    undup is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, see <http://www.gnu.org/licenses>
#

my $output = undef;
while (scalar(@ARGV)) {
    if ($ARGV[0] eq '-o') {
	shift @ARGV;
	$output = $ARGV[0];
	die("Missing file for -o\n") if (!defined($output)) ;
    } else {
	last;
    }
    shift @ARGV;
}
die("No output file specified\n") if (!defined($output)) ;

my $main = "// Collect all test suites\nTEST_SUITES {\n";
foreach my $tfile (@ARGV) {
    open(my $th,'<',$tfile) || die("$tfile: $!\n");
    my $suite = substr($tfile,0,length($tfile)-4);
    $decl .= "// Tests for $suite\n";
    $main .= "    TEST_SUITE_ADD($suite),\n";
    my $txt = "// Declare suite for $suite\nTEST_SUITE($suite) {\n";
    while (<$th>) {
	if (/^\s*TEST\s*\((.*)\)/) {
	    my $ut = $1;
	    #print "found: $ut in $suite\n";
	    $decl .= "TEST($ut);\n";
	    $txt .= "    TEST_ADD($ut),\n";
	}
    }
    close($th);
    $decl .= $txt;
    $decl .= "    TEST_SUITE_CLOSURE\n};\n";
}
$main .= "    TEST_SUITES_CLOSURE\n};\n";

open(my $out,'>',$output) || die("$output: $!\n");
print $out $decl;
print $out $main;
close($out);
